export const order = [
    'width',
    'height',
    'left',
    'top',
    'right',
    'bottom',
    'position',
    'backgroundColor',
    'backgroundImage',
    'backgroundPosition',
    'backgroundRepeat',
    'marginTop',
    'marginRight',
    'marginBottom',
    'marginLeft',
    // 'paddingTop',
    // 'paddingRight',
    // 'paddingBottom',
    // 'paddingLeft',
    // 'borderTopWidth',
    // 'borderRightWidth',
    // 'borderBottomWidth',
    // 'borderLeftWidth',
    // 'borderColor',
    // 'borderStyle',
    'color',
    'fontSize',
    'fontFamily',
    'fontWeight',
    'zIndex'
]

export default {
  height: {name: '高度'},
  width: {name: '宽度'},
  left: {name: '左X轴偏移'},
  top: {name: '顶Y轴偏移'},
  right: {name: '右X轴偏移'},
  bottom: {name: '底Y轴偏移'},
  position: {name: '布局方式', type: 'select', options: [
    {name: '无', value: ''},
    {name: '绝对布局', value: 'absolute'},
    {name: '相对布局', value: 'relative'},
    {name: '静态布局(不推荐)', value: 'static'},
    {name: '固定布局(不推荐)', value: 'fixed'}
  ]},
  backgroundColor: {name: '背景色'/*, type: 'color'*/},
  backgroundImage: {name: '背景图'},
  backgroundPosition: {name: '背景对齐', type: 'select', options: [
    {name: '无', value: ''},
    {name: '左上对齐', value: 'top left'},
    {name: '靠上水平居中', value: 'top center'},
    {name: '右上对齐', value: 'top right'},
    {name: '靠左垂直居中', value: 'center left'},
    {name: '居中对齐', value: 'center center'},
    {name: '靠右垂直居中', value: 'center right'},
    {name: '左下对齐', value: 'bottom left'},
    {name: '靠下水平居中', value: 'bottom center'},
    {name: '右下对齐', value: 'bottom right'}
  ]},
  backgroundRepeat: {name: '背景重复', type: 'select', options: [
    {name: '无', value: ''},
    {name: '不平铺', value: 'no-repeat'},
    {name: '双向平铺', value: 'repeat'},
    {name: '水平平铺', value: 'repeat-x'},
    {name: '垂直平铺', value: 'repeat-y'}
  ]},
  marginTop: {name: '外边距（上）'},
  marginRight: {name: '外边距（右）'},
  marginBottom: {name: '外边距（下）'},
  marginLeft: {name: '外边距（左）'},
  paddingTop: {name: '内边距（上）'},
  paddingRight: {name: '内边距（右）'},
  paddingBottom: {name: '内边距（下）'},
  paddingLeft: {name: '内边距（左）'},
  borderTopWidth: {name: '边框宽（上）'},
  borderRightWidth: {name: '边框宽（右）'},
  borderBottomWidth: {name: '边框宽（下）'},
  borderLeftWidth: {name: '边框宽（左）'},
  borderColor: {name: '边框颜色'/*, type: 'color'*/},
  borderStyle: {name: '边框样式', type: 'select', options: [
      {name: '无', value: 'none'},
      {name: '实线', value: 'solid'},
      {name: '虚线', value: 'dotted'},
      {name: '双线', value: 'double'}
  ]},
  color: {name: '字色'/*, type: 'color'*/},
  fontSize: {name: '字号'},
  fontFamily: {name: '字体'},
  fontWeight: {name: '字重', type: 'select', options: [
      {name: '无', value: ''},
      {name: '细', value: 'lighter'},
      {name: '标准', value: 'normal'},
      {name: '较粗', value: 'bold'},
      {name: '粗', value: 'bolder'},
  ]},
  zIndex: {name: '层级'}
}
